services:
  frontend:
    container_name: pu-frontend
    hostname: frontend
    volumes:
      - ./:/frontend
    command: bash -c "npm start"
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    cap_add:
      - SYS_PTRACE
    tty: true
    stdin_open: true
    network_mode: "host"
  env:
    container_name: pu-frontend
    hostname: frontend
    volumes:
      - ./:/frontend
    command: bash
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    cap_add:
      - SYS_PTRACE
    tty: true
    stdin_open: true
    network_mode: "host"